# Generated by Django 3.2.16 on 2022-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_location',
            field=models.CharField(choices=[('gap', 'Gap'), ('rail', 'Rail'), ('ledge', 'Ledge'), ('ramps', 'Ramps'), ('mini-ramp', 'Mini-Ramp'), ('halfpipe', 'Halfpipe'), ('street', 'Street'), ('park', 'Park'), ('other', 'Other')], default='normal', max_length=32),
        ),
    ]
