# Generated by Django 3.2.16 on 2022-12-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0002_auto_20221214_1252'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videofavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos_favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_videos', to='videos.videos')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'videos_favorites')},
            },
        ),
    ]
