# Generated by Django 3.2.16 on 2022-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_gslre8.jpg', upload_to='images/'),
        ),
    ]
