# Generated by Django 3.2.16 on 2022-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/volendam/image/upload/v1667372079/dm2euuvkpw2ww9yi0vky.jpg', upload_to='images/'),
        ),
    ]
