# Generated by Django 3.2.16 on 2022-12-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, default='Tell us a little about you'),
        ),
    ]
