# Generated by Django 3.2.16 on 2022-12-15 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0002_alter_postfavorites_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfavorites',
            old_name='post',
            new_name='post_favorite',
        ),
        migrations.AlterUniqueTogether(
            name='postfavorites',
            unique_together={('owner', 'post_favorite')},
        ),
    ]
