# Generated by Django 3.2.16 on 2022-12-14 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_auto_20221214_1252'),
        ('videolike', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together={('owner', 'video')},
        ),
    ]
